# retrieval
chunk_size: 800
chunk_overlap: 150
top_k: 4

# index
index_dir: faiss_index

# safety
min_context_chars: 200
refusal_text: "Not enough info in the docs."

# generation
ollama_model: llama3
temperature: 0.0
